CREATE TABLE `degree_salary` (
  `index` bigint(20) DEFAULT NULL,
  `Undergraduate Major` text,
  `Starting Median Salary` text,
  `Mid-Career Median Salary` text,
  `Percent change from Starting to Mid-Career Salary` double DEFAULT NULL,
  `Mid-Career 10th Percentile Salary` text,
  `Mid-Career 25th Percentile Salary` text,
  `Mid-Career 75th Percentile Salary` text,
  `Mid-Career 90th Percentile Salary` text,
  KEY `ix_degree_salary_index` (`index`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `school_info` (
  `schoolid` bigint(20) DEFAULT NULL,
  `program%.engineering_technology` double DEFAULT NULL,
  `demographics.ethn.non_resident_alien` double DEFAULT NULL,
  `program%.english` double DEFAULT NULL,
  `program%.resources` double DEFAULT NULL,
  `demographics.ethn.black` double DEFAULT NULL,
  `program%.social_science` double DEFAULT NULL,
  `program%.philosophy_religious` double DEFAULT NULL,
  `demographics.ethn.asian` double DEFAULT NULL,
  `program%.humanities` double DEFAULT NULL,
  `demographics.ethn.white` double DEFAULT NULL,
  `attendance.academic_year` bigint(20) DEFAULT NULL,
  `tuition.out_of_state` bigint(20) DEFAULT NULL,
  `program%.ethnic_cultural_gender` double DEFAULT NULL,
  `aid.federal_loan_rate` double DEFAULT NULL,
  `program%.public_administration_social_service` double DEFAULT NULL,
  `act_scores.midpoint.writing` double DEFAULT NULL,
  `school.name` text,
  `demographics.ethn.two_or_more` double DEFAULT NULL,
  `size` bigint(20) DEFAULT NULL,
  `grad_students` double DEFAULT NULL,
  `program%.computer` double DEFAULT NULL,
  `program%.engineering` double DEFAULT NULL,
  `act_scores.midpoint.cumulative` double DEFAULT NULL,
  `program%.biological` double DEFAULT NULL,
  `program%.communication` double DEFAULT NULL,
  `aid.loan_principal` double DEFAULT NULL,
  `sat_scores.average.overall` double DEFAULT NULL,
  `net_price.private.by_income_level.75001-110000` double DEFAULT NULL,
  `act_scores.midpoint.english` double DEFAULT NULL,
  `program%.communications_technology` double DEFAULT NULL,
  `program%.mechanic_repair_technology` double DEFAULT NULL,
  `aid.median_debt.income.30001_75000` double DEFAULT NULL,
  `aid.median_debt.completers.overall` double DEFAULT NULL,
  `program%.business_marketing` double DEFAULT NULL,
  `program%.physical_science` double DEFAULT NULL,
  `program%.library` double DEFAULT NULL,
  `tuition.in_state` bigint(20) DEFAULT NULL,
  `program%.history` double DEFAULT NULL,
  `program%.military` double DEFAULT NULL,
  `net_price.private.by_income_level.110001-plus` double DEFAULT NULL,
  `demographics.ethn.nhpi` double DEFAULT NULL,
  `program%.mathematics` double DEFAULT NULL,
  `program%.science_technology` double DEFAULT NULL,
  `program%.transportation` double DEFAULT NULL,
  `program%.legal` double DEFAULT NULL,
  `program%.construction` double DEFAULT NULL,
  `share_25_older` double DEFAULT NULL,
  `aid.median_debt.income.greater_than_75000` double DEFAULT NULL,
  `program%.architecture` double DEFAULT NULL,
  `program%.psychology` double DEFAULT NULL,
  `demographics.age_entry` bigint(20) DEFAULT NULL,
  `sat_scores.midpoint.writing` double DEFAULT NULL,
  `program%.multidiscipline` double DEFAULT NULL,
  `sat_scores.midpoint.math` double DEFAULT NULL,
  `net_price.private.by_income_level.48001-75000` double DEFAULT NULL,
  `program%.parks_recreation_fitness` double DEFAULT NULL,
  `demographics.median_family_income` bigint(20) DEFAULT NULL,
  `demographics.female_share` double DEFAULT NULL,
  `act_scores.midpoint.math` double DEFAULT NULL,
  `program%.health` double DEFAULT NULL,
  `aid.median_debt.noncompleters` double DEFAULT NULL,
  `program%.education` double DEFAULT NULL,
  `program%.security_law_enforcement` double DEFAULT NULL,
  `program%.theology_religious_vocation` double DEFAULT NULL,
  `program%.language` double DEFAULT NULL,
  `program%.visual_performing` double DEFAULT NULL,
  `aid.median_debt.income.0_30000` double DEFAULT NULL,
  `avg_net_price.private` double DEFAULT NULL,
  `net_price.private.by_income_level.30001-48000` double DEFAULT NULL,
  `school.ft_faculty_rate` double DEFAULT NULL,
  `demographics.ethn.aian` double DEFAULT NULL,
  `demographics.ethn.hispanic` double DEFAULT NULL,
  `program%.precision_production` double DEFAULT NULL,
  `sat_scores.midpoint.critical_reading` double DEFAULT NULL,
  `admission_rate.overall` double DEFAULT NULL,
  `program%.agriculture` double DEFAULT NULL,
  `demographics.ethn.unknown` double DEFAULT NULL,
  `net_price.private.by_income_level.0-30000` double DEFAULT NULL,
  `program%.family_consumer_science` double DEFAULT NULL,
  `demographics.avg_family_income` bigint(20) DEFAULT NULL,
  `program%.personal_culinary` double DEFAULT NULL,
  `school.faculty_salary` bigint(20) DEFAULT NULL,
  `aid.students_with_any_loan` double DEFAULT NULL,
  `avg_net_price.public` double DEFAULT NULL,
  `avg_net_price.program_year` text,
  `avg_net_price.other_academic_year` text,
  `net_price.public.by_income_level.0-30000` double DEFAULT NULL,
  `net_price.public.by_income_level.30001-48000` double DEFAULT NULL,
  `net_price.public.by_income_level.48001-75000` double DEFAULT NULL,
  `net_price.public.by_income_level.75001-110000` double DEFAULT NULL,
  `net_price.public.by_income_level.110001-plus` double DEFAULT NULL,
  `attendance.program_year` text,
  `tuition.program_year` text,
  KEY `ix_school_info_schoolid` (`schoolid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `school_salary` (
  `index` bigint(20) DEFAULT NULL,
  `School Name` text,
  `School Type` text,
  `Starting Median Salary` text,
  `Mid-Career Median Salary` text,
  `Mid-Career 10th Percentile Salary` text,
  `Mid-Career 25th Percentile Salary` text,
  `Mid-Career 75th Percentile Salary` text,
  `Mid-Career 90th Percentile Salary` text,
  `OPEID8` text,
  `Address` text,
  `City` text,
  `State` text,
  `Zip` text,
  `schoolid` double DEFAULT NULL,
  `Web` text,
  `OPEID6` double DEFAULT NULL,
  KEY `ix_school_salary_index` (`index`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

